# Generated by Django 4.1.3 on 2022-11-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0001_initial'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order', to='discount.discount')),
                ('tax', models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order', to='tax.tax')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
